datasets:
  raw:
    sales:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/sales_data.csv
      driver_params: {}

    google_search:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/google_search_data.csv
      driver_params: {}

    social_media:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/social_media_data.csv
      driver_params: {}

    product_manufacturer_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/product_manufacturer_list.csv
      driver_params: {}

    Theme_product_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_product_list.csv
      driver_params: {}

    Theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/Theme_list.csv
      driver_params: {}

  processed_data:
    sales:
      type: ds
      format: csv
      uri: ${core.data_base_path}/processed_data/sales_data.csv
      driver_params: {}

    google_search:
      type: ds
      format: csv
      uri: ${core.data_base_path}/processed_data/google_search_data.csv
      driver_params: {}

    social_media:
      type: ds
      format: csv
      uri: ${core.data_base_path}/processed_data/social_media_data.csv
      driver_params: {}

    product_manufacturer_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/processed_data/product_manufacturer_list.csv
      driver_params: {}

    Theme_product_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/processed_data/Theme_product_list.csv
      driver_params: {}

    Theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/processed_data/Theme_list.csv
      driver_params: {}

  merged_data:
    sales:
      type: ds
      format: csv
      uri: ${core.data_base_path}/merged_data/sales_data.csv
      driver_params: {}

    google_search:
      type: ds
      format: csv
      uri: ${core.data_base_path}/merged_data/google_search_data.csv
      driver_params: {}

    social_media:
      type: ds
      format: csv
      uri: ${core.data_base_path}/merged_data/social_media_data.csv
      driver_params: {}

    product_manufacturer_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/merged_data/product_manufacturer_list.csv
      driver_params: {}

    Theme_product_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/merged_data/Theme_product_list.csv
      driver_params: {}

    Theme_list:
      type: ds
      format: csv
      uri: ${core.data_base_path}/merged_data/Theme_list.csv
      driver_params: {}

  ground_truth_for_modelling:
    ground_truth:
      type: ds
      format: csv
      uri: ${core.data_base_path}/ground_truth_for_modelling/ground_truth_for_modelling.csv
      driver_params: {}

  train:
    ground_truth_for_modelling:
      features:
        type: ds
        format: csv
        uri: ${core.data_base_path}/train/ground_truth_for_modelling/features.csv
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: csv
        uri: ${core.data_base_path}/train/ground_truth_for_modelling/target.csv
        driver_params:
          save:
            index: False

  test:
    ground_truth_for_modelling:
      features:
        type: ds
        format: csv
        uri: ${core.data_base_path}/test/ground_truth_for_modelling/features.csv
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: csv
        uri: ${core.data_base_path}/test/ground_truth_for_modelling/target.csv
        driver_params:
          save:
            index: False